version: "3.9"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
